# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

__all__ = ["Ui_AuthWindow"]


class Ui_AuthWindow(object):
    def setupUi(self, AuthWindow):
        AuthWindow.setObjectName("AuthWindow")
        AuthWindow.resize(475, 350)
        AuthWindow.setMinimumSize(QtCore.QSize(475, 350))
        AuthWindow.setMaximumSize(QtCore.QSize(475, 350))
        AuthWindow.setBaseSize(QtCore.QSize(470, 350))
        AuthWindow.setStyleSheet("\n" "    background: white;\n" "")
        self.mainWidget = QtWidgets.QWidget(AuthWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.Email = QtWidgets.QTextEdit(self.mainWidget)
        self.Email.setGeometry(QtCore.QRect(40, 100, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Email.setFont(font)
        self.Email.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor)
        )
        self.Email.setStyleSheet(
            "QTextEdit {\n"
            "    border: none;border-radius: 5px;border-bottom: 1px solid blue;background: #eee;color: #444;\n"
            "}\n"
            "\n"
            "QTextEdit:hover {\n"
            "    background: white;color: #111;\n"
            "}\n"
            ""
        )
        self.Email.setObjectName("Email")
        self.Password = QtWidgets.QTextEdit(self.mainWidget)
        self.Password.setGeometry(QtCore.QRect(40, 170, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Password.setFont(font)
        self.Password.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor)
        )
        self.Password.setStyleSheet(
            "QTextEdit {\n"
            "    border: none;border-radius: 5px;border-bottom: 1px solid blue;background: #eee;color: #444;\n"
            "}\n"
            "\n"
            "QTextEdit:hover {\n"
            "    background: white;color: #111;\n"
            "}\n"
            ""
        )
        self.Password.setObjectName("Password")
        self.SignIn = QtWidgets.QPushButton(self.mainWidget)
        self.SignIn.setGeometry(QtCore.QRect(40, 280, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.SignIn.setFont(font)
        self.SignIn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SignIn.setStyleSheet(
            "QPushButton {\n"
            "    background: #72bac7;color: #edf7f9;font-weight: bold;border-radius: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: #65b4c3;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background: #7ec0cc;\n"
            "}\n"
            ""
        )
        self.SignIn.setObjectName("SignIn")
        self.Label = QtWidgets.QLabel(self.mainWidget)
        self.Label.setGeometry(QtCore.QRect(40, 20, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Label.setFont(font)
        self.Label.setStyleSheet(
            "QLabel {\n" "    color: #112c33;font-weight:bold;\n" "}"
        )
        self.Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Label.setObjectName("Label")
        self.RegistrationBtn = QtWidgets.QPushButton(self.mainWidget)
        self.RegistrationBtn.setGeometry(QtCore.QRect(40, 240, 75, 23))
        self.RegistrationBtn.setStyleSheet(
            "QPushButton {\n"
            "    background: rgba(0, 0, 0, 0);\n"
            "    border: none;\n"
            "    color: #276372;\n"
            "}"
        )
        self.RegistrationBtn.setObjectName("RegistrationBtn")
        self.HelpBtn = QtWidgets.QPushButton(self.mainWidget)
        self.HelpBtn.setGeometry(QtCore.QRect(334, 240, 91, 23))
        self.HelpBtn.setStyleSheet(
            "QPushButton {\n"
            "    background: rgba(0, 0, 0, 0);\n"
            "    border: none;\n"
            "    color: #276372;\n"
            "}"
        )
        self.HelpBtn.setObjectName("HelpBtn")
        AuthWindow.setCentralWidget(self.mainWidget)

        self.retranslateUi(AuthWindow)
        QtCore.QMetaObject.connectSlotsByName(AuthWindow)

    def retranslateUi(self, AuthWindow):
        _translate = QtCore.QCoreApplication.translate
        AuthWindow.setWindowTitle(_translate("AuthWindow", "MainWindow"))
        self.Email.setHtml(
            _translate(
                "AuthWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.Email.setPlaceholderText(_translate("AuthWindow", "Почта"))
        self.Password.setHtml(
            _translate(
                "AuthWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.Password.setPlaceholderText(_translate("AuthWindow", "Пароль"))
        self.SignIn.setText(_translate("AuthWindow", "Войти"))
        self.Label.setText(_translate("AuthWindow", "Вход"))
        self.RegistrationBtn.setText(_translate("AuthWindow", "Регистрация"))
        self.HelpBtn.setText(_translate("AuthWindow", "Забыли пароль?"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     AuthWindow = QtWidgets.QMainWindow()
#     ui = Ui_AuthWindow()
#     ui.setupUi(AuthWindow)
#     AuthWindow.show()
#     sys.exit(app.exec_())
