# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pkg/gui/resources/content.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QStandardItem, QStandardItemModel


class StandardItem(QStandardItem):
    def __init__(
        self, txt="", font_size=12, set_bold=False, color=QtGui.QColor(0, 0, 0)
    ):
        super().__init__()

        fnt = QtGui.QFont("Open Sans", font_size)
        fnt.setBold(set_bold)

        self.setEditable(False)
        self.setForeground(color)
        self.setFont(fnt)
        self.setText(txt)


class Ui_ContentWindow(object):
    def setupUi(self, ContentWindow):
        ContentWindow.setObjectName("ContentWindow")
        ContentWindow.resize(1106, 738)
        self.mainWidget = QtWidgets.QWidget(ContentWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.section = QtWidgets.QTreeView(self.mainWidget)
        self.section.setGeometry(QtCore.QRect(0, 0, 256, 711))
        self.section.setStyleSheet("border:none;background:white;")
        self.section.setAlternatingRowColors(False)
        self.section.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.section.setObjectName("section")
        self.section.setHeaderHidden(True)
        # ------------------------------
        tree_model = QStandardItemModel()
        root_node = tree_model.invisibleRootItem()
        section1 = StandardItem("Раздел 1", 16, set_bold=True)

        themes1 = StandardItem("График функции", 14)
        themes2 = StandardItem("Тригонометрия", 14)
        themes3 = StandardItem("Логарифмическая функция", 14)
        section1.appendRows([themes1, themes2, themes3])

        theme1 = StandardItem("Квадратичная функция", 12, color=QtGui.QColor(0, 0, 255))
        theme2 = StandardItem(
            "График функции \ny = ( (x + a) (x + b) ) / x",
            12,
            color=QtGui.QColor(0, 0, 255),
        )
        theme3 = StandardItem(
            "График функции \ny = ( x^2 - a ) / x", 12, color=QtGui.QColor(0, 0, 255)
        )
        theme4 = StandardItem(
            "График функции \ny = e^(x - 1) / x", 12, color=QtGui.QColor(0, 0, 255)
        )
        theme5 = StandardItem(
            "График функции \ny = xe^x", 12, color=QtGui.QColor(0, 0, 255)
        )
        theme6 = StandardItem(
            "График функции \ny = (a - x^3) / ( x^2 )",
            12,
            color=QtGui.QColor(0, 0, 255),
        )
        theme7 = StandardItem(
            "График функции \ny = -( x / (x + 2) ) ^ 2",
            12,
            color=QtGui.QColor(0, 0, 255),
        )
        theme8 = StandardItem(
            "График функции \ny = x^3 - ax",
            12,
            color=QtGui.QColor(0, 0, 255),
        )
        theme9 = StandardItem(
            "График функции \ny = x^4 + ax^3 + bx^2 + cx + z",
            12,
            color=QtGui.QColor(0, 0, 255),
        )
        theme10 = StandardItem(
            "График функции \ny = x^( 1/2 )",
            12,
            color=QtGui.QColor(0, 0, 255),
        )
        themes1.appendRows(
            [
                theme1,
                theme2,
                theme3,
                theme4,
                theme5,
                theme6,
                theme7,
                theme8,
                theme9,
                theme10,
            ]
        )

        theme6 = StandardItem("Формула cos x", 12, color=QtGui.QColor(0, 0, 255))
        theme7 = StandardItem("Формула sin x", 12, color=QtGui.QColor(0, 0, 255))
        theme8 = StandardItem("Формула tg x", 12, color=QtGui.QColor(0, 0, 255))
        theme9 = StandardItem("Формула ctg x", 12, color=QtGui.QColor(0, 0, 255))
        themes2.appendRows([theme6, theme7, theme8, theme9])

        theme1 = StandardItem(
            "График функции \ny = x lnx", 12, color=QtGui.QColor(0, 0, 255)
        )
        theme2 = StandardItem(
            "График функции \ny = log (a) x", 12, color=QtGui.QColor(0, 0, 255)
        )
        themes3.appendRows([theme1, theme2])

        root_node.appendRow(section1)
        self.section.setModel(tree_model)
        self.section.expandAll()
        # ------------------------------
        self.scrollArea = QtWidgets.QScrollArea(self.mainWidget)
        self.scrollArea.setGeometry(QtCore.QRect(260, 0, 841, 711))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 839, 709))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        ContentWindow.setCentralWidget(self.mainWidget)
        self.menubar = QtWidgets.QMenuBar(ContentWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        ContentWindow.setMenuBar(self.menubar)
        self.profile = QtWidgets.QAction(ContentWindow)
        self.profile.setObjectName("profile")
        self.editProfile = QtWidgets.QAction(ContentWindow)
        self.editProfile.setObjectName("editProfile")
        self.exitProfile = QtWidgets.QAction(ContentWindow)
        self.exitProfile.setObjectName("exitProfile")
        self.action_3 = QtWidgets.QAction(ContentWindow)
        self.action_3.setObjectName("action_3")
        self.action_6 = QtWidgets.QAction(ContentWindow)
        self.action_6.setObjectName("action_6")
        self.menu.addAction(self.profile)
        self.menu.addAction(self.editProfile)
        self.menu.addSeparator()
        self.menu.addAction(self.exitProfile)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(ContentWindow)
        QtCore.QMetaObject.connectSlotsByName(ContentWindow)

    def retranslateUi(self, ContentWindow):
        _translate = QtCore.QCoreApplication.translate
        ContentWindow.setWindowTitle(_translate("ContentWindow", "MainWindow"))
        self.menu.setTitle(_translate("ContentWindow", "Профиль"))
        self.profile.setText(_translate("ContentWindow", "Посмотреть"))
        self.editProfile.setText(_translate("ContentWindow", "Изменить"))
        self.exitProfile.setText(_translate("ContentWindow", "Выйти"))
        self.action_3.setText(_translate("ContentWindow", "На фон"))
        self.action_6.setText(_translate("ContentWindow", "Полностью закрыть"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ContentWindow = QtWidgets.QMainWindow()
    ui = Ui_ContentWindow()
    ui.setupUi(ContentWindow)
    ContentWindow.show()
    sys.exit(app.exec_())
