# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

__all__ = ["Ui_HelpWindow"]


class Ui_HelpWindow(object):
    def setupUi(self, HelpWindow):
        HelpWindow.setObjectName("HelpWindow")
        HelpWindow.resize(475, 275)
        HelpWindow.setMinimumSize(QtCore.QSize(475, 275))
        HelpWindow.setMaximumSize(QtCore.QSize(475, 275))
        self.mainWidget = QtWidgets.QWidget(HelpWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.Email = QtWidgets.QTextEdit(self.mainWidget)
        self.Email.setGeometry(QtCore.QRect(40, 100, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Email.setFont(font)
        self.Email.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor)
        )
        self.Email.setStyleSheet(
            "QTextEdit {\n"
            "    border: none;border-radius: 5px;border-bottom: 1px solid blue;background: #eee;color: #444;\n"
            "}\n"
            "\n"
            "QTextEdit:hover {\n"
            "    background: white;color: #111;\n"
            "}\n"
            ""
        )
        self.Email.setObjectName("Email")
        self.Label = QtWidgets.QLabel(self.mainWidget)
        self.Label.setGeometry(QtCore.QRect(40, 20, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Label.setFont(font)
        self.Label.setStyleSheet(
            "QLabel {\n" "    color: #112c33;font-weight:bold;\n" "}"
        )
        self.Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Label.setObjectName("Label")
        self.SendMail = QtWidgets.QPushButton(self.mainWidget)
        self.SendMail.setGeometry(QtCore.QRect(40, 210, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.SendMail.setFont(font)
        self.SendMail.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SendMail.setStyleSheet(
            "QPushButton {\n"
            "    background: #72bac7;color: #edf7f9;font-weight: bold;border-radius: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: #65b4c3;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background: #7ec0cc;\n"
            "}\n"
            ""
        )
        self.SendMail.setObjectName("SendMail")
        self.LoginBtn = QtWidgets.QPushButton(self.mainWidget)
        self.LoginBtn.setGeometry(QtCore.QRect(40, 170, 31, 23))
        self.LoginBtn.setStyleSheet(
            "QPushButton {\n"
            " background: rgba(0, 0, 0, 0);\n"
            "border: none;\n"
            "color: #276372;\n"
            "}"
        )
        self.LoginBtn.setObjectName("LoginBtn")
        HelpWindow.setCentralWidget(self.mainWidget)

        self.retranslateUi(HelpWindow)
        QtCore.QMetaObject.connectSlotsByName(HelpWindow)

    def retranslateUi(self, HelpWindow):
        _translate = QtCore.QCoreApplication.translate
        HelpWindow.setWindowTitle(_translate("HelpWindow", "MainWindow"))
        self.Email.setHtml(
            _translate(
                "HelpWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.Email.setPlaceholderText(_translate("HelpWindow", "Почта"))
        self.Label.setText(_translate("HelpWindow", "Восстановление пароля"))
        self.SendMail.setText(_translate("HelpWindow", "Получить сообщение"))
        self.LoginBtn.setText(_translate("HelpWindow", "Войти"))
