# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfileWindow(object):
    def setupUi(self, ProfileWindow):
        ProfileWindow.setObjectName("ProfileWindow")
        ProfileWindow.resize(312, 130)
        self.mainwidget = QtWidgets.QWidget(ProfileWindow)
        self.mainwidget.setObjectName("mainwidget")
        self.emailLabel = QtWidgets.QLabel(self.mainwidget)
        self.emailLabel.setGeometry(QtCore.QRect(20, 60, 81, 16))
        self.emailLabel.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.emailLabel.setObjectName("emailLabel")
        self.emailValue = QtWidgets.QLabel(self.mainwidget)
        self.emailValue.setGeometry(QtCore.QRect(120, 60, 171, 16))
        self.emailValue.setObjectName("emailValue")
        self.editProfile = QtWidgets.QPushButton(self.mainwidget)
        self.editProfile.setGeometry(QtCore.QRect(30, 90, 261, 23))
        self.editProfile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editProfile.setStyleSheet(
            "QPushButton {\n"
            "    background: #72bac7;color: #edf7f9;font-weight: bold;border-radius: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background: #65b4c3;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "   background: #7ec0cc;\n"
            "}\n"
            ""
        )
        self.editProfile.setObjectName("editProfile")
        self.label = QtWidgets.QLabel(self.mainwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        ProfileWindow.setCentralWidget(self.mainwidget)

        self.retranslateUi(ProfileWindow)
        QtCore.QMetaObject.connectSlotsByName(ProfileWindow)

    def retranslateUi(self, ProfileWindow):
        _translate = QtCore.QCoreApplication.translate
        ProfileWindow.setWindowTitle(_translate("ProfileWindow", "MainWindow"))
        self.emailLabel.setText(_translate("ProfileWindow", "Почта"))
        self.emailValue.setText(_translate("ProfileWindow", "-"))
        self.editProfile.setText(_translate("ProfileWindow", "Изменить данные"))
        self.label.setText(_translate("ProfileWindow", "Ваш профиль"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ProfileWindow = QtWidgets.QMainWindow()
    ui = Ui_ProfileWindow()
    ui.setupUi(ProfileWindow)
    ProfileWindow.show()
    sys.exit(app.exec_())
