# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

__all__ = ["Ui_RegistrationWindow"]


class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        RegistrationWindow.setObjectName("RegistrationWindow")
        RegistrationWindow.resize(475, 420)
        RegistrationWindow.setMinimumSize(QtCore.QSize(475, 420))
        RegistrationWindow.setMaximumSize(QtCore.QSize(475, 420))
        RegistrationWindow.setStyleSheet("background: white;")
        self.mainWidget = QtWidgets.QWidget(RegistrationWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.Email = QtWidgets.QTextEdit(self.mainWidget)
        self.Email.setGeometry(QtCore.QRect(40, 100, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Email.setFont(font)
        self.Email.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor)
        )
        self.Email.setStyleSheet(
            "QTextEdit {\n"
            "    border: none;border-radius: 5px;border-bottom: 1px solid blue;background: #eee;color: #444;\n"
            "}\n"
            "\n"
            "QTextEdit:hover {\n"
            "    background: white;color: #111;\n"
            "}\n"
            ""
        )
        self.Email.setObjectName("Email")
        self.Label = QtWidgets.QLabel(self.mainWidget)
        self.Label.setGeometry(QtCore.QRect(40, 20, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Label.setFont(font)
        self.Label.setStyleSheet(
            "QLabel {\n" "    color: #112c33;font-weight:bold;\n" "}"
        )
        self.Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Label.setObjectName("Label")
        self.SignUp = QtWidgets.QPushButton(self.mainWidget)
        self.SignUp.setGeometry(QtCore.QRect(40, 350, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.SignUp.setFont(font)
        self.SignUp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SignUp.setStyleSheet(
            "QPushButton {\n"
            "    background: #72bac7;color: #edf7f9;font-weight: bold;border-radius: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: #65b4c3;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "    background: #7ec0cc;\n"
            "}\n"
            ""
        )
        self.SignUp.setObjectName("SignUp")
        self.Password = QtWidgets.QTextEdit(self.mainWidget)
        self.Password.setGeometry(QtCore.QRect(40, 170, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Password.setFont(font)
        self.Password.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor)
        )
        self.Password.setStyleSheet(
            "QTextEdit {\n"
            "    border: none;border-radius: 5px;border-bottom: 1px solid blue;background: #eee;color: #444;\n"
            "}\n"
            "\n"
            "QTextEdit:hover {\n"
            "    background: white;color: #111;\n"
            "}\n"
            ""
        )
        self.Password.setObjectName("Password")
        self.PasswordConfirm = QtWidgets.QTextEdit(self.mainWidget)
        self.PasswordConfirm.setGeometry(QtCore.QRect(40, 240, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.PasswordConfirm.setFont(font)
        self.PasswordConfirm.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor)
        )
        self.PasswordConfirm.setStyleSheet(
            "QTextEdit {\n"
            "    border: none;border-radius: 5px;border-bottom: 1px solid blue;background: #eee;color: #444;\n"
            "}\n"
            "\n"
            "QTextEdit:hover {\n"
            "    background: white;color: #111;\n"
            "}\n"
            ""
        )
        self.PasswordConfirm.setObjectName("PasswordConfirm")
        self.LoginBtn = QtWidgets.QPushButton(self.mainWidget)
        self.LoginBtn.setGeometry(QtCore.QRect(40, 310, 31, 23))
        self.LoginBtn.setStyleSheet(
            "QPushButton {\n"
            " background: rgba(0, 0, 0, 0);\n"
            "border: none;\n"
            "color: #276372;\n"
            "}"
        )
        self.LoginBtn.setObjectName("LoginBtn")
        RegistrationWindow.setCentralWidget(self.mainWidget)

        self.retranslateUi(RegistrationWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistrationWindow)

    def retranslateUi(self, RegistrationWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistrationWindow.setWindowTitle(
            _translate("RegistrationWindow", "MainWindow")
        )
        self.Email.setHtml(
            _translate(
                "RegistrationWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.Email.setPlaceholderText(_translate("RegistrationWindow", "Почта"))
        self.Label.setText(_translate("RegistrationWindow", "Регистрация"))
        self.SignUp.setText(_translate("RegistrationWindow", "Зарегистрировать"))
        self.Password.setHtml(
            _translate(
                "RegistrationWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.Password.setPlaceholderText(_translate("RegistrationWindow", "Пароль"))
        self.PasswordConfirm.setHtml(
            _translate(
                "RegistrationWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
            )
        )
        self.PasswordConfirm.setPlaceholderText(
            _translate("RegistrationWindow", "Подтвердите пароль")
        )
        self.LoginBtn.setText(_translate("RegistrationWindow", "Войти"))
