# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(322, 328)
        self.mainwidget = QtWidgets.QWidget(SettingsWindow)
        self.mainwidget.setObjectName("mainwidget")
        self.send_new_password = QtWidgets.QPushButton(self.mainwidget)
        self.send_new_password.setGeometry(QtCore.QRect(30, 180, 261, 23))
        self.send_new_password.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_new_password.setStyleSheet(
            "QPushButton {\n"
            "    background: #72bac7;color: #edf7f9;font-weight: bold;border-radius: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background: #65b4c3;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "   background: #7ec0cc;\n"
            "}\n"
            ""
        )
        self.send_new_password.setObjectName("send_new_password")
        self.new_password_value = QtWidgets.QTextEdit(self.mainwidget)
        self.new_password_value.setGeometry(QtCore.QRect(10, 70, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_password_value.setFont(font)
        self.new_password_value.setObjectName("new_password_value")
        self.real_pass_value = QtWidgets.QTextEdit(self.mainwidget)
        self.real_pass_value.setGeometry(QtCore.QRect(10, 120, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.real_pass_value.setFont(font)
        self.real_pass_value.setObjectName("real_pass_value")
        self.common_label = QtWidgets.QLabel(self.mainwidget)
        self.common_label.setGeometry(QtCore.QRect(10, 10, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.common_label.setFont(font)
        self.common_label.setAlignment(QtCore.Qt.AlignCenter)
        self.common_label.setObjectName("common_label")
        self.send_new_email = QtWidgets.QPushButton(self.mainwidget)
        self.send_new_email.setGeometry(QtCore.QRect(30, 290, 261, 23))
        self.send_new_email.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send_new_email.setStyleSheet(
            "QPushButton {\n"
            "    background: #72bac7;color: #edf7f9;font-weight: bold;border-radius: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "   background: #65b4c3;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "   background: #7ec0cc;\n"
            "}\n"
            ""
        )
        self.send_new_email.setObjectName("send_new_email")
        self.new_email_value = QtWidgets.QTextEdit(self.mainwidget)
        self.new_email_value.setGeometry(QtCore.QRect(10, 230, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_email_value.setFont(font)
        self.new_email_value.setObjectName("new_email_value")
        SettingsWindow.setCentralWidget(self.mainwidget)

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "MainWindow"))
        self.send_new_password.setText(_translate("SettingsWindow", "Изменить пароль"))
        self.new_password_value.setPlaceholderText(
            _translate("SettingsWindow", "Новый пароль")
        )
        self.real_pass_value.setPlaceholderText(
            _translate("SettingsWindow", "Действующий пароль")
        )
        self.common_label.setText(_translate("SettingsWindow", "Изменить данные"))
        self.send_new_email.setText(_translate("SettingsWindow", "Изменить почту"))
        self.new_email_value.setPlaceholderText(
            _translate("SettingsWindow", "Новая почта")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    SettingsWindow = QtWidgets.QMainWindow()
    ui = Ui_SettingsWindow()
    ui.setupUi(SettingsWindow)
    SettingsWindow.show()
    sys.exit(app.exec_())
